# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Crimson Desert Mod Manager

a = Analysis(
    ['src/cdmm/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[('cdmm.ico', '.')],
    hiddenimports=[
        'cdmm.gui.main_window',
        'cdmm.gui.setup_dialog',
        'cdmm.gui.import_widget',
        'cdmm.gui.conflict_view',
        'cdmm.gui.mod_list_model',
        'cdmm.gui.asi_panel',
        'cdmm.gui.test_mod_dialog',
        'cdmm.gui.workers',
        'cdmm.gui.bug_report',
        'cdmm.engine.snapshot_manager',
        'cdmm.engine.delta_engine',
        'cdmm.engine.import_handler',
        'cdmm.engine.conflict_detector',
        'cdmm.engine.apply_engine',
        'cdmm.engine.mod_manager',
        'cdmm.engine.test_mod_checker',
        'cdmm.archive.transactional_io',
        'cdmm.archive.hashlittle',
        'cdmm.archive.papgt_manager',
        'cdmm.archive.format_parsers.base',
        'cdmm.archive.format_parsers.pabgb_parser',
        'cdmm.archive.format_parsers.paac_parser',
        'cdmm.archive.format_parsers.pamt_parser',
        'cdmm.asi.asi_manager',
        'cdmm.storage.database',
        'cdmm.storage.config',
        'cdmm.storage.game_finder',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CrimsonDesertModManager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='cdmm.ico',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
